# Generated by Django 4.2.1 on 2023-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao_curta", models.TextField(max_length=300)),
                ("descricao_Longa", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="produto_imagens/%y/%m/"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("preco_marketing", models.FloatField(default=0)),
                ("preco_marketing_promocional", models.FloatField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("V", "Variação"), ("S", "Simples")],
                        default="v",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
